function pageNavi(q){(function(d){var f=configSummary,c={postperpage:f.postPerPage,numshowpage:f.numshowpage,previous:"&#171;",next:"&#187;",loadAjax:!0,thumbnailSize:f.thumbnailSize,summaryLength:f.summaryLength,viewmodedefault:f.defaultView,cookielist:"list",cookiegrid:"grid",monthName:Alldefaultconfig.monthName,slideffect:f.slideffect,maxImage:f.maxImage,slideSpeed:f.slideSpeed,BackupImage:f.BackupImage},c=d.extend({},c,q),g=location.href,l,e,k,h,r=function(a){var b="";nomerkiri=parseInt(c.numshowpage/
2);nomerkiri==c.numshowpage-nomerkiri&&(c.numshowpage=2*nomerkiri+1);mulai=k-nomerkiri;1>mulai&&(mulai=1);maksimal=parseInt(a/c.postperpage)+1;maksimal-1==a/c.postperpage&&(maksimal-=1);akhir=mulai+c.numshowpage-1;akhir>maksimal&&(akhir=maksimal);a=parseInt(k)-1;1<k&&(b=2==k?"page"==e?b+('<span class="showpage"><a href="/">'+c.previous+"</a></span>"):b+('<span class="showpageNum"><a href="/search/label/'+h+"?&max-results="+c.postperpage+'">'+c.previous+"</a></span>"):"page"==e?b+('<span class="showpageNum"><a class="xpagex" href="#" alt="'+
a+'">'+c.previous+"</a></span>"):b+('<span class="showpageNum"><a class="xlabelx" href="#" alt="'+a+'">'+c.previous+"</a></span>"));1<mulai&&(b="page"==e?b+'<span class="showpageNum"><a href="/">1</a></span>':b+('<span class="showpageNum"><a href="/search/label/'+h+"?&max-results="+c.postperpage+'">1</a></span>'));2<mulai&&(b+='<span class="dotxpage"> ... </span>');for(a=mulai;a<=akhir;a++)b=k==a?b+('<span class="showpagePoint">'+a+"</span>"):1==a?"page"==e?b+'<span class="showpageNum"><a href="/">1</a></span>':
b+('<span class="showpageNum"><a href="/search/label/'+h+"?&max-results="+c.postperpage+'">1</a></span>'):"page"==e?b+('<span class="showpageNum"><a href="#" class="xpagex" alt="'+a+'">'+a+"</a></span>"):b+('<span class="showpageNum"><a href="#" class="xlabelx" alt="'+a+'">'+a+"</a></span>");akhir<maksimal-1&&(b+='<span class="dotxpage"> ... </span>');akhir<maksimal&&(b="page"==e?b+('<span class="showpageNum"><a href="#" class="xpagex" alt="'+maksimal+'">'+maksimal+"</a></span>"):b+('<span class="showpageNum"><a href="#" class="xlabelx" alt="'+
maksimal+'">'+maksimal+"</a></span>"));a=parseInt(k)+1;k<maksimal&&(b="page"==e?b+('<span class="showpageNum"><a href="#" class="xpagex" alt="'+a+'">'+c.next+"</a></span>"):b+('<span class="showpageNum"><a href="#" class="xlabelx" alt="'+a+'">'+c.next+"</a></span>"));a=document.getElementsByName("pageArea");for(var g=document.getElementById("blog-pager"),f=0;f<a.length;f++)a[f].innerHTML=b;a&&0<a.length&&(b="");g&&(g.innerHTML=b);d("#blog-pager").css("display","block");d("#blog-pager a.xpagex, #blog-pager a.xlabelx").click(function(){c.loadAjax&&
d(".loadingpost").show();var a=d(this).attr("alt");jsonstart=(a-1)*c.postperpage;l=a;"page"==e?d.get("/feeds/posts/summary?start-index="+jsonstart+"&max-results=1&alt=json-in-script",m,"jsonp"):d.get("/feeds/posts/summary/-/"+h+"?start-index="+jsonstart+"&max-results=1&alt=json-in-script",m,"jsonp");return!1});d(".loadingpost").hide()},n=function(a){a=parseInt(a.feed.openSearch$totalResults.$t,10);r(a)},p=function(){var a=g;-1!=a.indexOf("/search/label/")&&(h=-1!=a.indexOf("?updated-max")?a.substring(a.indexOf("/search/label/")+
14,a.indexOf("?updated-max")):-1!=a.indexOf("?&max")?a.substring(a.indexOf("/search/label/")+14,a.indexOf("?&max")):a.substr(a.lastIndexOf("/")));-1==a.indexOf("?q=")&&-1==a.indexOf(".html")&&(-1==a.indexOf("/search/label/")?(e="page",k=-1!=g.indexOf("#PageNo=")?g.substring(g.indexOf("#PageNo=")+8,g.length):1,d.get("/feeds/posts/summary?max-results=1&alt=json-in-script",n,"jsonp")):(e="label",-1==a.indexOf("&max-results=")&&(c.postperpage=21),k=-1!=g.indexOf("#PageNo=")?g.substring(g.indexOf("#PageNo=")+
8,g.length):1,d.get("/feeds/posts/summary/-/"+h+"?max-results=1&alt=json-in-script",n,"jsonp")))};p();var m=function(a){post=a.feed.entry[0];a=post.published.$t.substring(0,19)+post.published.$t.substring(23,29);a=encodeURIComponent(a);var b="page"==e?"/search?updated-max="+a+"&max-results="+c.postperpage+"#PageNo="+l:"/search/label/"+h+"?updated-max="+a+"&max-results="+c.postperpage+"#PageNo="+l;if(c.loadAjax){var f=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi;d.get(b,"html").done(function(a){a=
d("<div></div>").append(a.replace(f,"")).find("div.blog-posts").children(".date-outer");a.find(".post-summary").each(function(){var a,b,f=[],g,e,k;e=a="";b=d(this).parent(".post-body").children("textarea").val();f=b.replace(/\/s[0-9]+(\-c)?\//g,"/"+c.thumbnailSize+"/");k=b.replace(/<(.*?)>/g,"").replace(/[\n\r]+/g," ");parens=d(this).parents(".post");e=parens.find(".post-title.entry-title a").attr("href");titlex=parens.find(".post-title.entry-title a").text();if(null!=(f=f.match(/https?:\/\/.+?\.(jpg|gif|png|bmp)/gi))){var h=
[];d.each(f,function(a,b){-1===d.inArray(b,h)&&h.push(b)});if(!0===c.slideffect&&1<h.length){g=c.maxImage>h.length?h.length:c.maxImage;for(b=0;b<g;b++)a+='<li><a title="'+titlex+'" href="'+e+'"><img alt="'+titlex+'" src="'+h[b]+'"/></a></li>';a='<div class="thumbimgslide"><div class="slideximg"><ul class="imgslide">'+a+"</ul></div></div>";var l=d(this).attr("id");setTimeout(function(){d("#"+l+" .slideximg").flexslider({animation:"fade",selector:".imgslide > li",slideshowSpeed:c.slideSpeed})},20)}else a=
'<a class="thumbimgx" title="'+titlex+'" href="'+e+'"><img class="post-thumbnail" src="'+h[0]+'" alt="'+titlex+'"></a>'}else a=null!=(g=b.match(/(\?v=|\&v=|\/\d\/|\/embed\/|\/v\/|\.be\/)([a-zA-Z0-9\-\_]+)/))?'<a class="thumbimgx" title="'+titlex+'" href="'+e+'"><img class="post-thumbnail" src="http://img.youtube.com/vi/'+g[2]+'/0.jpg" alt="'+titlex+'"/></a>':'<a title="'+titlex+'" class="thumbimgx" href="'+e+'"><img class="post-thumbnail" src="'+c.BackupImage.replace(/\/s[0-9]+(\-c)?\//,"/"+c.thumbnailSize+
"/")+'" alt="'+titlex+'"/></a>';e=a+'<strong><a class="titlex" href="'+e+'">'+titlex+"</a></strong><p>"+k.substring(0,c.summaryLength)+"&hellip;</p>";d(this).html(e)});d("div.blog-posts").html(a);datenya({monthName:c.monthName});viewMode({viewmodedefault:c.viewmodedefault,cookielist:c.cookielist,cookiegrid:c.cookiegrid});g=b;p();window._gaq&&window._gaq.push(["_trackPageview",c.olderPostsLink]);window.gapi&&window.gapi.plusone&&window.gapi.plusone.go&&window.gapi.plusone.go();window.disqus_shortname&&
d.getScript("http://"+window.disqus_shortname+".disqus.com/blogger_index.js");window.FB&&window.FB.XFBML&&window.FB.XFBML.parse&&window.FB.XFBML.parse()})}else location.href=b}})(jQuery)};